[package]
name = "apalis-core"
version = "0.3.6"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Core for Apalis: simple, extensible multithreaded background processing for Rust"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures =  { version = "0.3", default-features = false, features=["async-await"] }
tower = { version = "0.4", optional = true, default-features = false }
pin-project-lite = "0.2.9"
tokio =  { version = "1", optional = true, default-features = false, features = ["sync", "time", "rt", "io-util", "rt-multi-thread", "signal"] }
thiserror = "1"
log = "0.4"
http = "0.2.7"
uuid = { version = "1.3", features = ["serde", "v4"] }
strum = { version = "0.24", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
tracing-futures = { version = "0.2.5", optional = true, default-features = false }
sentry-core =  { version= "0.30", optional = true, default-features = false }
metrics = { version = "0.18", optional = true, default-features = false }
metrics-exporter-prometheus = { version = "0.8", optional = true, default-features = false }
async-trait = { version = "0.1", optional = true, default-features = false }
dashmap = { version = "5", optional = true, default-features = false }
once_cell = { version = "1", optional = true, default-features = false }
petgraph =  { version = "0.6.2", optional = true, default-features = false }

[features]
default = [ "tower-util", "storage", "job-service", "worker"]
job-service = []
tower-util = ["tower/util"]
worker = ["tokio", "async-trait"]
storage = ["async-trait", "tokio"]
broker = ["dashmap", "once_cell", "petgraph"]
layers = ["sentry", "prometheus", "trace", "retry", "timeout", "limit", "filter", "extensions"]
sentry = ["sentry-core"]
prometheus = ["metrics", "metrics-exporter-prometheus"]
trace = ["tracing-futures/std-future", "tracing-futures/tokio"]
retry = ["tower/retry"]
timeout = ["tower/timeout"]
limit = ["tower/limit"]
filter = ["tower/filter"]
extensions = []

[dependencies.tracing]
default_features = false
version = "0.1"

[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true


[dev-dependencies]
tokio = { version = "1.6.0", features = ["macros"]}
