[package]
name = "apalis-core"
version = "0.4.4"
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Core for apalis: simple, extensible multithreaded background processing for Rust"
categories = ["concurrency"]
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = { version = "1.0", features = ["derive"] }
futures = { version = "0.3", features = ["async-await"] }
tower = { version = "0.4", features = ["util"] }
pin-project-lite = "0.2.12"
tokio = { version = "1", features = ["rt", "net"], optional = true }
async-std = { version = "1", optional = true }
smol = { version = "1.3", optional = true }
smol-timeout = { version = "0.6", optional = true }
thiserror = "1.0.47"
log = "0.4"
http = { version = "0.2.9", optional = true }
strum = { version = "0.25", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "serde",
] }
tracing-futures = { version = "0.2.5", optional = true, default-features = false }
sentry-core = { version = "0.31.5", optional = true, default-features = false }
metrics = { version = "0.21", optional = true, default-features = false }
metrics-exporter-prometheus = { version = "0.12", optional = true, default-features = false }
async-trait = { version = "0.1" }
graceful-shutdown = { version = "0.2", features = ["stream", "tokio-timeout"] }
ulid = "1.0.0"
# Needed only for sentry reporting
uuid = { version = "1.4", optional = true }
async-stream = "0.3"

[dependencies.document-features]
version = "0.2"
optional = true

[features]
default = ["tokio-comp", "extensions"]
storage = ["extensions"]
mq = ["extensions"]
expose = []
layers = [
    "sentry",
    "prometheus",
    "trace",
    "retry",
    "timeout",
    "limit",
    "filter",
    "extensions",
]
sentry = ["sentry-core", "ulid/uuid", "uuid"]
prometheus = ["metrics", "metrics-exporter-prometheus"]
trace = ["tracing-futures/std-future", "tracing-futures/tokio"]
retry = ["tower/retry"]
timeout = ["tower/timeout"]
limit = ["tower/limit"]
filter = ["tower/filter"]
extensions = ["http"]
async-std-comp = ["async-std", "smol-timeout", "smol"]
tokio-comp = ["tokio"]
docsrs = ["document-features"]

[dependencies.tracing]
default_features = false
version = "0.1"

[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true


[dev-dependencies]
tokio = { version = "1.31.0", features = ["macros", "rt", "sync"] }
