[package]
name = "apalis-workflow"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
petgraph = { version = "0.8.2", features = ["serde-1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tower = { version = "0.5", features = ["full"] }
apalis-core = { path = "../../packages/apalis-core", version = "0.7.1", default-features = false, features = [
    "sleep",
    "json",
] }
tokio = { version = "1.37.0", features = ["macros", "rt", "sync"] }
futures = "0.3.30"
thiserror = "2.0.0"
