[package]
name = "apalis-workflow"
version = "0.1.0-alpha.2"
edition.workspace = true
repository.workspace = true
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
license = "MIT"
description = "A flexible and composable task workflow engine for rust"

[dependencies]
petgraph = { version = "0.8.2", features = ["serde-1"] }
serde = { version = "1.0", features = ["derive"] }
tower = { version = "0.5", features = ["util"], default-features = false }
apalis-core = { path = "../apalis-core", version = "1.0.0-alpha.2", default-features = false, features = [
    "sleep",
    "json",
] }
futures = "0.3.30"
thiserror = "2.0.0"

[dev-dependencies]
serde_json = "1"
tokio = { version = "1.37.0", features = ["macros", "rt", "sync"] }
