[package]
name = "email-service"
version = "0.1.0"
edition = "2018"

[dependencies]
apalis = { path = "../../", default-features = false }
futures-util = "0.3.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"