[package]
name = "workflow"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
tower = { version = "0.5", features = ["util"] }
tokio = { version = "1", features = ["full"] }
apalis = { path = "../../apalis", features = ["limit", "catch-panic", "retry"] }
apalis-workflow = { path = "../../apalis-workflow" }
apalis-core = { path = "../../apalis-core", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing-subscriber = "0.3.20"
futures = "0.3"

[dependencies.tracing]
default-features = false
version = "0.1"
