[package]
name = "apalis-cron"
version = "0.5.0-alpha.0"
edition = "2021"
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
license = "MIT"
description = "A simple yet extensible library for cron-like job scheduling for rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apalis-core = { path = "../../packages/apalis-core", version = "0.5.0-alpha.0", default-features = false, features = [
    "sleep",
    "json",
] }
cron = "0.12.0"
futures = "0.3"
tower = { version = "0.4" }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "serde",
] }
async-stream = "0.3.5"
async-std = { version = "1.12.0", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
apalis-core = { path = "../../packages/apalis-core" }
apalis = { path = "../../", default-features = false, features = ["retry"] }
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["tokio-comp"]
async-std-comp = ["async-std"]
tokio-comp = ["tokio/net"]

[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
