[package]
name = "apalis-cron"
version = "0.4.0-alpha.1"
edition = "2021"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
license = "MIT"
description = "A simple yet extensible library for cron-like job scheduling for rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apalis-core = { path = "../../packages/apalis-core", version = "0.4.0-alpha.1" }
cron = "0.11.0"
futures = "0.3"
tower = { version = "0.4" }
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
tokio = { version = "1", features = ["time"] }
async-stream = "0.3.3"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
apalis-core = { path = "../../packages/apalis-core", version = "0.4.0-alpha.1", features=["extensions", "retry"] }
serde = { version = "1.0", features = ["derive"] }

[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
