on:
  push:
    paths:
      - "packages/apalis-sql/src/lib.rs"
      - "packages/apalis-sql/postgres.rs"
      - "packages/apalis-sql/src/migrations/postgres/**"
      - "packages/apalis-sql/src/Cargo.toml"
      - ".github/workflows/postgres.yaml"
  pull_request:
    paths:
      - "packages/apalis-sql/src/lib.rs"
      - "packages/apalis-sql/src/postgres.rs"
      - "packages/apalis-sql/src/migrations/postgres/**"
      - "packages/apalis-sql/src/Cargo.toml"
      - ".github/workflows/postgres.yaml"

name: Postgres CI

jobs:
  test-sqlite:
    name: Test Suite Postgres
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost/postgres
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test --no-default-features --features postgres,migrate,tokio-comp -- --test-threads=1
        working-directory: packages/apalis-sql